/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AggregatorsRouteImport } from './routes/aggregators'
import { Route as HeadOfficeRouteImport } from './routes/head-office'
import { Route as InventoryManagerRouteImport } from './routes/inventory-manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PosTillRouteImport } from './routes/pos-till'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PurchasingRouteImport } from './routes/purchasing'
import { Route as StoreManagerRouteImport } from './routes/store-manager'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as VendorPortalRouteImport } from './routes/vendor-portal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AggregatorsRoute = AggregatorsRouteImport.update({
  id: '/aggregators',
  path: '/aggregators',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadOfficeRoute = HeadOfficeRouteImport.update({
  id: '/head-office',
  path: '/head-office',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryManagerRoute = InventoryManagerRouteImport.update({
  id: '/inventory-manager',
  path: '/inventory-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PosTillRoute = PosTillRouteImport.update({
  id: '/pos-till',
  path: '/pos-till',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingRoute = PurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreManagerRoute = StoreManagerRouteImport.update({
  id: '/store-manager',
  path: '/store-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorPortalRoute = VendorPortalRouteImport.update({
  id: '/vendor-portal',
  path: '/vendor-portal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aggregators': typeof AggregatorsRoute
  '/head-office': typeof HeadOfficeRoute
  '/inventory-manager': typeof InventoryManagerRoute
  '/login': typeof LoginRoute
  '/pos-till': typeof PosTillRoute
  '/pricing': typeof PricingRoute
  '/purchasing': typeof PurchasingRoute
  '/store-manager': typeof StoreManagerRoute
  '/super-admin': typeof SuperAdminRoute
  '/vendor-portal': typeof VendorPortalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aggregators': typeof AggregatorsRoute
  '/head-office': typeof HeadOfficeRoute
  '/inventory-manager': typeof InventoryManagerRoute
  '/login': typeof LoginRoute
  '/pos-till': typeof PosTillRoute
  '/pricing': typeof PricingRoute
  '/purchasing': typeof PurchasingRoute
  '/store-manager': typeof StoreManagerRoute
  '/super-admin': typeof SuperAdminRoute
  '/vendor-portal': typeof VendorPortalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aggregators': typeof AggregatorsRoute
  '/head-office': typeof HeadOfficeRoute
  '/inventory-manager': typeof InventoryManagerRoute
  '/login': typeof LoginRoute
  '/pos-till': typeof PosTillRoute
  '/pricing': typeof PricingRoute
  '/purchasing': typeof PurchasingRoute
  '/store-manager': typeof StoreManagerRoute
  '/super-admin': typeof SuperAdminRoute
  '/vendor-portal': typeof VendorPortalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aggregators'
    | '/head-office'
    | '/inventory-manager'
    | '/login'
    | '/pos-till'
    | '/pricing'
    | '/purchasing'
    | '/store-manager'
    | '/super-admin'
    | '/vendor-portal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aggregators'
    | '/head-office'
    | '/inventory-manager'
    | '/login'
    | '/pos-till'
    | '/pricing'
    | '/purchasing'
    | '/store-manager'
    | '/super-admin'
    | '/vendor-portal'
  id:
    | '__root__'
    | '/'
    | '/aggregators'
    | '/head-office'
    | '/inventory-manager'
    | '/login'
    | '/pos-till'
    | '/pricing'
    | '/purchasing'
    | '/store-manager'
    | '/super-admin'
    | '/vendor-portal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AggregatorsRoute: typeof AggregatorsRoute
  HeadOfficeRoute: typeof HeadOfficeRoute
  InventoryManagerRoute: typeof InventoryManagerRoute
  LoginRoute: typeof LoginRoute
  PosTillRoute: typeof PosTillRoute
  PricingRoute: typeof PricingRoute
  PurchasingRoute: typeof PurchasingRoute
  StoreManagerRoute: typeof StoreManagerRoute
  SuperAdminRoute: typeof SuperAdminRoute
  VendorPortalRoute: typeof VendorPortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aggregators': {
      id: '/aggregators'
      path: '/aggregators'
      fullPath: '/aggregators'
      preLoaderRoute: typeof AggregatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/head-office': {
      id: '/head-office'
      path: '/head-office'
      fullPath: '/head-office'
      preLoaderRoute: typeof HeadOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-manager': {
      id: '/inventory-manager'
      path: '/inventory-manager'
      fullPath: '/inventory-manager'
      preLoaderRoute: typeof InventoryManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-till': {
      id: '/pos-till'
      path: '/pos-till'
      fullPath: '/pos-till'
      preLoaderRoute: typeof PosTillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing': {
      id: '/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof PurchasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-manager': {
      id: '/store-manager'
      path: '/store-manager'
      fullPath: '/store-manager'
      preLoaderRoute: typeof StoreManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-portal': {
      id: '/vendor-portal'
      path: '/vendor-portal'
      fullPath: '/vendor-portal'
      preLoaderRoute: typeof VendorPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AggregatorsRoute: AggregatorsRoute,
  HeadOfficeRoute: HeadOfficeRoute,
  InventoryManagerRoute: InventoryManagerRoute,
  LoginRoute: LoginRoute,
  PosTillRoute: PosTillRoute,
  PricingRoute: PricingRoute,
  PurchasingRoute: PurchasingRoute,
  StoreManagerRoute: StoreManagerRoute,
  SuperAdminRoute: SuperAdminRoute,
  VendorPortalRoute: VendorPortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
